export const TECH_CATEGORY_MAP = {
  '.net core': 'languages',
  '.net maui': 'frontend',
  angular: 'frontend',
  angularjs: 'frontend',
  android: 'frontend',
  'background service': 'backend',
  blazor: 'frontend',
  'c#': 'languages',
  'c# .net': 'languages',
  'c# .net core': 'languages',
  cefsharp: 'frontend',
  css: 'frontend',
  'docker compose': 'infrastructure',
  docker: 'infrastructure',
  'entity framework': 'backend',
  'file processing': 'backend',
  'github actions': 'devops',
  hacs: 'infrastructure',
  javascript: 'languages',
  jql: 'backend',
  json: 'backend',
  'jira rest api': 'backend',
  mariadb: 'database',
  mongodb: 'database',
  mudblazor: 'frontend',
  mvc: 'patterns',
  mvvm: 'patterns',
  mysql: 'database',
  'octopus deploy': 'devops',
  proxmox: 'infrastructure',
  python: 'languages',
  rabbitmq: 'infrastructure',
  react: 'frontend',
  rollup: 'frontend',
  signalr: 'backend',
  skiasharp: 'frontend',
  spa: 'patterns',
  'sql server': 'database',
  't-sql': 'languages',
  teamcity: 'devops',
  'three.js': 'frontend',
  typescript: 'languages',
  'web api': 'backend',
  'windows forms': 'frontend',
  wpf: 'frontend',
  'xamarin.forms': 'frontend',
};

export function getTechCategory(tech) {
  return TECH_CATEGORY_MAP[String(tech).trim().toLowerCase()] || 'tech-other';
}
